### ISSUE TITLE
Additional validation rules

### ISSUE THREAD

**Issue by jrtashjian** [jrtashjian/omniform#11]
The "required" rule is the only optional validation rule applied to form fields. Appropriate validation rules should be applied to each field on the PHP side, such as requiring an email value for email fields, a URL for URL fields, and so on.

**Comment by BrianHenryIE** [comment]
I haven't used this myself, but FYI: https://github.com/stellarwp/field-conditions

**Comment by jrtashjian** [comment]
That looks great! I've actually already included and started the implementation using [Respect/Validation](https://github.com/Respect/Validation) library and seems to include everything needed.

**Comment by BrianHenryIE** [comment]
Have you looked at https://wordpress.org/plugins/block-visibility/ and similar for showing/hiding fields? Might be something to think of in context of validation.
