### ISSUE TITLE
OmniForm localization

### ISSUE THREAD

**Issue by piermario** [jrtashjian/omniform#13]
Hello JR!

First of all congratulations on OmniForm landing on the WordPress Plugin Directory! 

I went to check it right away as I'd like to translate the plugin into Italian. However, I didn't see any language/translation option. Are you planning to eventually release language packs, so that we can localize the plugin? 

Thanks again for your awesome work! :)

**Comment by jrtashjian** [comment]
Thank you so much!

Yes, OmniForm should be translatable via [translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/omniform/). I did some testing last night specifically around local translations and it looks like I'll have to tweak some things to get it working 100%.
